services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: investment
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://app:app@db:5432/investment
      PORT: "5050"
    ports:
      - "5050:5050"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
